### ISSUE TITLE
Nomos-v2   VS     DF2K-OST

### ISSUE THREAD

**Issue by Feynman1999** [neosr-project/neosr#89]
Hello！ have you compared the performance of real-esrgan( RRDB blocks ) trained on these two datasets?

**Comment by neosr-project** [comment]
Hi! I have not published a 'formal' analysis on both datasets, unfortunately. However, empirically, it gives better metrics. We have discussed a bit about it on [issue 86](https://github.com/neosr-project/neosr/issues/86). @Phhofm will publish an article soon comparing DF2k against distilled versions, so if you're interested in this subject he might be able to share some data with you.
