### ISSUE TITLE
about dunet discriminator

### ISSUE THREAD

**Issue by Feynman1999** [neosr-project/neosr#90]
Can DUNET be used as a substitute for Patch U-Net in real-esrgan training? Would the effect be better?

**Comment by Feynman1999** [comment]
> Probably. However, I didn't run any tests to say for sure. You can contact [the original author](https://github.com/umzi2/DUnet) for more information.

@umzi2  can you share some point of view， thanks~

**Comment by umzi2** [comment]
> > Probably. However, I didn't run any tests to say for sure. You can contact [the original author](https://github.com/umzi2/DUnet) for more information.
> 
> @umzi2 can you share some point of view， thanks~
I apologize for the delayed response. In general, DUNet is essentially a U-Net with the upsampling block replaced by [DySample](https://arxiv.org/pdf/2308.15085), which provides smoother results. Across all tests, DUNet demonstrated greater stability and outperformed U-Net; however, it requires more memory.
![изображение](https://github.com/user-attachments/assets/e150ce7b-f652-40a7-a284-24f70d183b31)

**Comment by Feynman1999** [comment]
> > > Probably. However, I didn't run any tests to say for sure. You can contact [the original author](https://github.com/umzi2/DUnet) for more information.
> > 
> > 
> > @umzi2 can you share some point of view， thanks~
> 
> I apologize for the delayed response. In general, DUNet is essentially a U-Net with the upsampling block replaced by [DySample](https://arxiv.org/pdf/2308.15085), which provides smoother results. Across all tests, DUNet demonstrated greater stability and outperformed U-Net; however, it requires more memory. ![изображение](https://private-user-images.githubusercontent.com/131161226/388804908-e150ce7b-f652-40a7-a284-24f70d183b31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNjY0MTcsIm5iZiI6MTczMjI2NjExNywicGF0aCI6Ii8xMzExNjEyMjYvMzg4ODA0OTA4LWUxNTBjZTdiLWY2NTItNDBhNy1hMjg0LTI0ZjcwZDE4M2IzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQwOTAxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWFiOTFmZWIzYjkwNjIyNWNiMzMwODg1YTI5YjU4NmQ1MTUyY2JjN2UxNmYzMzhjN2FkZTE2ZjI0MzUzZmY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lztgV82HUWFqXhTn2TihQuGonpK8DBsV1lGnp_24Lg8)

You're already doing great; thank you! I noticed that in your repo (https://github.com/umzi2/DUnet), the SSIM metric is better. Is this a super-resolution model trained under the ESRGAN setup? If it's Real-ESRGAN, have you tried it?

**Comment by umzi2** [comment]
> You're already doing great; thank you! I noticed that in your repo (https://github.com/umzi2/DUnet), the SSIM metric is better. Is this a super-resolution model trained under the ESRGAN setup? If it's Real-ESRGAN, have you tried it?

![изображение](https://github.com/user-attachments/assets/0ce71451-0591-4e0e-8319-59ec00f20fd3)
